### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by stav-ros** [kiharalab/DiffModeler#1]
Hi, I am encountering the following error when running prediction using fasta sequences command as follows:

`python3 main.py --mode=1 -F=/Projects/cryosparc_map.mrc -P=/Projects/sequences.txt --config=config/diffmodeler.json --contour=0.07 --resolution=6
`
After running for a few moments, the program hangs with the following:

```
RUNNING
Creating result file: fasta-R20240129-132703-0904-89657085-p1m.ffdp-subject-jpeg.jpg
Creating result file: fasta-R20240129-132703-0904-89657085-p1m.submission.params
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    fitting_dict = fasta2pool(params,save_path)
  File "/DiffModeler/ops/fasta2pool.py", line 93, in fasta2pool
    download_pdb(pdb_id,current_chain_dir,final_pdb_path)
  File "/DiffModeler/ops/fasta_searchdb.py", line 50, in download_pdb
    chain_id = pdb_id.split("_")[1]
IndexError: list index out of range
```
What could be the issue?
Thanks

**Comment by wang3702** [comment]
I think it fails to download pdb but I don't know why it happens since I never encountered this before. Could you please share the input and output intermediate files to me via email: wang3702@uw.edu. You can also share a link here, which can help me to debug. For emergent tasks, please try our server: https://em.kiharalab.org/algorithm/DiffModeler(seq). That includes a local database which should have no problems.
